sudo: required
services:
  - docker
language: node_js
env:
  - CXX=g++-4.8
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.8
node_js:
  - 4
  - 6
