sudo: required
services:
  - docker
language: node_js
env:
  - CXX=g++-4.8
addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.8
node_js:
  - stable
  - 10
  - 8
  - 6
